# Get accounts belonging to a user
GET http://localhost:3000/api/accounts/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MywiZmlyc3RfbmFtZSI6IlJ5YW4iLCJsYXN0X25hbWUiOiJKYWNrc29uIiwiZW1haWwiOiJyeWFuQGdtYWlsLmNvbSIsImRhdGVfb2ZfYmlydGgiOiIyMDIzLTExLTAxVDAwOjAwOjAwLjAwMFoiLCJpYXQiOjE2OTg5MTIxNzZ9.bnJ20hASqZm0KjdQbHKvSLTWWLpAILF1zaJMM_hDqsE

###

# Create a new account
POST http://localhost:3000/api/accounts/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MywiZmlyc3RfbmFtZSI6IlJ5YW4iLCJsYXN0X25hbWUiOiJKYWNrc29uIiwiZW1haWwiOiJyeWFuQGdtYWlsLmNvbSIsImRhdGVfb2ZfYmlydGgiOiIyMDIzLTExLTAxVDAwOjAwOjAwLjAwMFoiLCJpYXQiOjE2OTg5MTIxNzZ9.bnJ20hASqZm0KjdQbHKvSLTWWLpAILF1zaJMM_hDqsE

{
    "accountName": "test_account4",
    "accountNumber": 264958502
}

###

# Get an individual account
GET http://localhost:3000/api/accounts/3
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MywiZmlyc3RfbmFtZSI6IlJ5YW4iLCJsYXN0X25hbWUiOiJKYWNrc29uIiwiZW1haWwiOiJyeWFuQGdtYWlsLmNvbSIsImRhdGVfb2ZfYmlydGgiOiIyMDIzLTExLTAxVDAwOjAwOjAwLjAwMFoiLCJpYXQiOjE2OTg5MTIxNzZ9.bnJ20hASqZm0KjdQbHKvSLTWWLpAILF1zaJMM_hDqsE

###

# Update an account
PATCH http://localhost:3000/api/accounts/3
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MywiZmlyc3RfbmFtZSI6IlJ5YW4iLCJsYXN0X25hbWUiOiJKYWNrc29uIiwiZW1haWwiOiJyeWFuQGdtYWlsLmNvbSIsImRhdGVfb2ZfYmlydGgiOiIyMDIzLTExLTAxVDAwOjAwOjAwLjAwMFoiLCJpYXQiOjE2OTg5MTIxNzZ9.bnJ20hASqZm0KjdQbHKvSLTWWLpAILF1zaJMM_hDqsE

{
    "accountName": "test_account3",
    "accountNumber": 279570812
}

###

# Deposit funds into an account
POST http://localhost:3000/api/accounts/4
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MywiZmlyc3RfbmFtZSI6IlJ5YW4iLCJsYXN0X25hbWUiOiJKYWNrc29uIiwiZW1haWwiOiJyeWFuQGdtYWlsLmNvbSIsImRhdGVfb2ZfYmlydGgiOiIyMDIzLTExLTAxVDAwOjAwOjAwLjAwMFoiLCJpYXQiOjE2OTg5MTIxNzZ9.bnJ20hASqZm0KjdQbHKvSLTWWLpAILF1zaJMM_hDqsE

{
    "depositAmount": 5000.00,
    "category": "Personal"
}

###

POST http://localhost:3000/api/accounts/4
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MywiZmlyc3RfbmFtZSI6IlJ5YW4iLCJsYXN0X25hbWUiOiJKYWNrc29uIiwiZW1haWwiOiJyeWFuQGdtYWlsLmNvbSIsImRhdGVfb2ZfYmlydGgiOiIyMDIzLTExLTAxVDAwOjAwOjAwLjAwMFoiLCJpYXQiOjE2OTg5MTIxNzZ9.bnJ20hASqZm0KjdQbHKvSLTWWLpAILF1zaJMM_hDqsE

{
    "transactionType": "Expense",
    "amount": 500.00,
    "category": "Transportation"
}

###